### ISSUE TITLE
Method finding and compilation is slow

### ISSUE THREAD

**Issue by Kaiserchen** [BrandonShar/stack-overflow-buddy#1]
When using Stackoverflowbuddy in a hot loop this causes some performance issues. 

Maybe we can have a pluggable cache? so that the eval'd function name can be looked up by method-name and number of parameters? that could potentially speed up things.

Keep up the good stuff :P

**Comment by Kaiserchen** [comment]
ah no worries, it actually caches already

**Comment by BrandonShar** [comment]
Glad to have preemptively solved your issue! :smile:
